apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: admin.fctf2025.fpt
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-mvc-svc 
                port:
                  number: 8000
  tls:
    - hosts:
        - admin.fctf2025.fpt
      secretName: admin-tls
