# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: jenkins-ingress
#   namespace: jenkins
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-dev
#     nginx.ingress.kubernetes.io/proxy-body-size: "0"
# spec:
#   rules:
#     - host: jenkinszmn0zjiwmju.fctf.cloud
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: jenkins
#                 port:
#                   number: 8080
#   tls:
#     - hosts:
#         - jenkinszmn0zjiwmju.fctf.cloud
#       secretName: jenkins-tls