apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: contestant-be-svc
spec:
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  selector:
    app: contestant-be
  type: ClusterIP
