apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-center-sa
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-center-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-center-sa-binding
subjects:
  - kind: ServiceAccount
    name: deployment-center-sa
    namespace: app
roleRef:
  kind: ClusterRole
  name: deployment-center-sa-role
  apiGroup: rbac.authorization.k8s.io
