apiVersion: v1
kind: ConfigMap
metadata:
  name: common-be-cm
  namespace: app
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  PRIVATE_KEY: "emdungdepzai" # dùng để giao tiếp với giữa các service backend
  SECRET_KEY: "emdungdepzai" # dùng để mã hóa token authentication
  NFS_MOUNT_PATH: "/mnt/nfs/data"
  DEPLOYMENT_SERVICE_API: "http://deployment-center-svc.app.svc.cluster.local:5020"
  ARGO_WORKFLOWS_URL: "http://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows/argo"
  TCP_DOMAIN: "challenge-zg9uj3rfagfja19tzq-dev.fctf.cloud"