apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: contestant-portal-svc
spec:
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  selector:
    app: contestant-portal
  type: ClusterIP