apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: contestant-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contestant-portal
  template:
    metadata:
      labels:
        app: contestant-portal
    spec:
      containers:
        - name: contestant-portal
          image: quachuoiscontainer/fctf:contestant-portal-prod-v3.6.0
          ports:
            - name: http-client
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 0.1
              memory: 100Mi
            limits:
              cpu: 0.15
              memory: 150Mi
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 3
