apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: admin-mvc-svc
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Chọn số trong dải 30000–32767
  selector:
    app: admin-mvc
  type: NodePort
